# Generated by Django 4.0.1 on 2022-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=32, verbose_name='Apellido')),
                ('age', models.IntegerField(default=0, verbose_name='Edad')),
                ('height', models.FloatField(default=0.0, verbose_name='Altura')),
                ('status', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
        ),
    ]
