# Generated by Django 4.0.1 on 2022-01-29 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id', '-age']},
        ),
        migrations.AlterModelTable(
            name='person',
            table='persons',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre trabajo')),
                ('status', models.BooleanField(default=True, verbose_name='Estatus')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='app1.person', verbose_name='Persona')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
